name: flutter_weather_app
description: Weather app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  anim_search_bar: ^2.0.3
  geocoding: ^2.0.4
  geolocator: ^10.0.1
  dio: ^5.3.2
  flutter_riverpod: ^2.1.3
  freezed_annotation: ^2.2.0
  freezed: ^2.3.2
  state_notifier: ^0.7.2+1
  sqflite: ^2.2.2
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true